apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-a-disk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-a-deployment
  labels:
    app: db-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-a
  template:
    metadata:
      labels:
        app: db-a
    spec:
      containers:
        - name: db-a
          image: dikadhr/mysql:assessment
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              subPath: "mysql"
              name: mysqldb
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: webapp-secrets
                  key: mysql_password
      volumes:
        - name: mysqldb
          persistentVolumeClaim:
            claimName: db-a-disk
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-db-service
spec:
  selector:
    app: db-a
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306