---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webapp-disk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: dikadhr/wordpress:assessment
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/var/www/html"
              name: webapp-disk
          env:
            - name: WORDPRESS_DB_HOST
              value: webapp-db-service
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: webapp-secrets
                  key: mysql_password
      volumes:
        - name: webapp-disk
          persistentVolumeClaim:
            claimName: webapp-disk
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: webapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer